package roles

var NativeRoles = []any{
	&Anon{},
	&Authenticated{},
	&Authenticator{},
	&DashboardUser{},
	&PgCheckpoint{},
	&PgDatabaseOwner{},
	&PgExecuteServerProgram{},
	&PgMonitor{},
	&PgReadAllData{},
	&PgReadAllSettings{},
	&PgReadAllStats{},
	&PgReadServerFiles{},
	&PgSignalBackend{},
	&PgStatScanTables{},
	&PgWriteAllData{},
	&PgWriteServerFiles{},
	&Pgbouncer{},
	&PgsodiumKeyholder{},
	&PgsodiumKeyiduser{},
	&PgsodiumKeymaker{},
	&Postgres{},
	&ServiceRole{},
	&SupabaseAdmin{},
	&SupabaseAuthAdmin{},
	&SupabaseFunctionsAdmin{},
	&SupabaseReadOnlyUser{},
	&SupabaseReplicationAdmin{},
	&SupabaseStorageAdmin{},
}
