/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type ColumnsBody struct {
	TableId            int32                               `json:"table_id"`
	Name               string                              `json:"name"`
	Type_              string                              `json:"type"`
	DefaultValue       any                                 `json:"default_value,omitempty"`
	DefaultValueFormat *AnyOfcolumnsBodyDefaultValueFormat `json:"default_value_format,omitempty"`
	IsIdentity         bool                                `json:"is_identity,omitempty"`
	IdentityGeneration *AnyOfcolumnsBodyIdentityGeneration `json:"identity_generation,omitempty"`
	IsNullable         bool                                `json:"is_nullable,omitempty"`
	IsPrimaryKey       bool                                `json:"is_primary_key,omitempty"`
	IsUnique           bool                                `json:"is_unique,omitempty"`
	Comment            string                              `json:"comment,omitempty"`
	Check              string                              `json:"check,omitempty"`
}
