/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type ColumnprivilegesBody1 struct {
	ColumnId      string                                   `json:"column_id"`
	Grantee       string                                   `json:"grantee"`
	PrivilegeType *AnyOfcolumnprivilegesBody1PrivilegeType `json:"privilege_type"`
}
