/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type InlineResponse2003 struct {
	Id      int32                           `json:"id"`
	Schema  string                          `json:"schema"`
	Name    string                          `json:"name"`
	Comment *AnyOfinlineResponse2003Comment `json:"comment"`
	Columns []InlineResponse2001            `json:"columns,omitempty"`
}
