/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type TablesIdBody struct {
	Name                 string                            `json:"name,omitempty"`
	Schema               string                            `json:"schema,omitempty"`
	RlsEnabled           bool                              `json:"rls_enabled,omitempty"`
	RlsForced            bool                              `json:"rls_forced,omitempty"`
	ReplicaIdentity      *AnyOftablesIdBodyReplicaIdentity `json:"replica_identity,omitempty"`
	ReplicaIdentityIndex string                            `json:"replica_identity_index,omitempty"`
	PrimaryKeys          []TablesidPrimaryKeys             `json:"primary_keys,omitempty"`
	Comment              string                            `json:"comment,omitempty"`
}
