/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type SchemasIdBody struct {
	Name  string `json:"name,omitempty"`
	Owner string `json:"owner,omitempty"`
}
