/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type RolesidConfig struct {
	Op    *AnyOfrolesidConfigOp `json:"op"`
	Path  string                `json:"path"`
	Value string                `json:"value,omitempty"`
}
