/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type ColumnsIdBody struct {
	Name               string                                `json:"name,omitempty"`
	Type_              string                                `json:"type,omitempty"`
	DropDefault        bool                                  `json:"drop_default,omitempty"`
	DefaultValue       any                                   `json:"default_value,omitempty"`
	DefaultValueFormat *AnyOfcolumnsIdBodyDefaultValueFormat `json:"default_value_format,omitempty"`
	IsIdentity         bool                                  `json:"is_identity,omitempty"`
	IdentityGeneration *AnyOfcolumnsIdBodyIdentityGeneration `json:"identity_generation,omitempty"`
	IsNullable         bool                                  `json:"is_nullable,omitempty"`
	IsUnique           bool                                  `json:"is_unique,omitempty"`
	Comment            string                                `json:"comment,omitempty"`
	Check              *AnyOfcolumnsIdBodyCheck              `json:"check,omitempty"`
}
