/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type InlineResponse2008 struct {
	RelationId int32                        `json:"relation_id"`
	Schema     string                       `json:"schema"`
	Name       string                       `json:"name"`
	Kind       *AnyOfinlineResponse2008Kind `json:"kind"`
	Privileges []TableprivilegesPrivileges  `json:"privileges"`
}
