/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type InlineResponse2001 struct {
	TableId            int32                                      `json:"table_id"`
	Schema             string                                     `json:"schema"`
	Table              string                                     `json:"table"`
	Id                 string                                     `json:"id"`
	OrdinalPosition    int32                                      `json:"ordinal_position"`
	Name               string                                     `json:"name"`
	DefaultValue       any                                        `json:"default_value"`
	DataType           string                                     `json:"data_type"`
	Format             string                                     `json:"format"`
	IsIdentity         bool                                       `json:"is_identity"`
	IdentityGeneration *AnyOfinlineResponse2001IdentityGeneration `json:"identity_generation"`
	IsGenerated        bool                                       `json:"is_generated"`
	IsNullable         bool                                       `json:"is_nullable"`
	IsUpdatable        bool                                       `json:"is_updatable"`
	IsUnique           bool                                       `json:"is_unique"`
	Enums              []string                                   `json:"enums"`
	Check              *AnyOfinlineResponse2001Check              `json:"check"`
	Comment            *AnyOfinlineResponse2001Comment            `json:"comment"`
}
