/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type InlineResponse20010 struct {
	Id               int32                                    `json:"id"`
	Schema           string                                   `json:"schema"`
	Name             string                                   `json:"name"`
	RlsEnabled       bool                                     `json:"rls_enabled"`
	RlsForced        bool                                     `json:"rls_forced"`
	ReplicaIdentity  *AnyOfinlineResponse20010ReplicaIdentity `json:"replica_identity"`
	Bytes            int32                                    `json:"bytes"`
	Size             string                                   `json:"size"`
	LiveRowsEstimate int32                                    `json:"live_rows_estimate"`
	DeadRowsEstimate int32                                    `json:"dead_rows_estimate"`
	Comment          *AnyOfinlineResponse20010Comment         `json:"comment"`
	Columns          []InlineResponse2001                     `json:"columns,omitempty"`
	PrimaryKeys      []TablesPrimaryKeys                      `json:"primary_keys"`
	Relationships    []TablesRelationships                    `json:"relationships"`
}
