/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type FunctionArg struct {
	Mode       string `json:"mode,omitempty"`
	Name       string `json:"name,omitempty"`
	TypeId     int32  `json:"type_id,omitempty"`
	HasDefault bool   `json:"has_default,omitempty"`
}
