/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type Function struct {
	Id                     int64         `json:"id,omitempty"`
	Schema                 string        `json:"schema,omitempty"`
	Name                   string        `json:"name,omitempty"`
	Language               string        `json:"language,omitempty"`
	Definition             string        `json:"definition,omitempty"`
	CompleteStatement      string        `json:"complete_statement,omitempty"`
	Args                   []FunctionArg `json:"args,omitempty"`
	ArgumentTypes          string        `json:"argument_types,omitempty"`
	IdentityArgumentTypes  string        `json:"identity_argument_types,omitempty"`
	ReturnTypeId           int64         `json:"return_type_id,omitempty"`
	ReturnType             string        `json:"return_type,omitempty"`
	ReturnTypeRelationId   int64         `json:"return_type_relation_id,omitempty"`
	IsSetReturningFunction bool          `json:"is_set_returning_function,omitempty"`
	Behavior               string        `json:"behavior,omitempty"`
	SecurityDefiner        bool          `json:"security_definer,omitempty"`
	ConfigParams           interface{}   `json:"config_params,omitempty"`
}
