/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type TablesPrimaryKeys struct {
	Schema    string `json:"schema"`
	TableName string `json:"table_name"`
	Name      string `json:"name"`
	TableId   int32  `json:"table_id"`
}
