/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type InlineResponse2007 struct {
	Id                int32                              `json:"id"`
	Name              string                             `json:"name"`
	IsSuperuser       bool                               `json:"is_superuser"`
	CanCreateDb       bool                               `json:"can_create_db"`
	CanCreateRole     bool                               `json:"can_create_role"`
	InheritRole       bool                               `json:"inherit_role"`
	CanLogin          bool                               `json:"can_login"`
	IsReplicationRole bool                               `json:"is_replication_role"`
	CanBypassRls      bool                               `json:"can_bypass_rls"`
	ActiveConnections int32                              `json:"active_connections"`
	ConnectionLimit   int32                              `json:"connection_limit"`
	Password          string                             `json:"password"`
	ValidUntil        *AnyOfinlineResponse2007ValidUntil `json:"valid_until"`
	Config            any                                `json:"config"`
}
