/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type InlineResponse20011 struct {
	Id          int32                            `json:"id"`
	Schema      string                           `json:"schema"`
	Name        string                           `json:"name"`
	IsUpdatable bool                             `json:"is_updatable"`
	Comment     *AnyOfinlineResponse20011Comment `json:"comment"`
	Columns     []InlineResponse2001             `json:"columns,omitempty"`
}
