/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type TableprivilegesBody struct {
	RelationId    int32                                  `json:"relation_id"`
	Grantee       string                                 `json:"grantee"`
	PrivilegeType *AnyOftableprivilegesBodyPrivilegeType `json:"privilege_type"`
	IsGrantable   bool                                   `json:"is_grantable,omitempty"`
}
