/*
 * postgres-meta
 *
 * A REST API to manage your Postgres database
 *
 * API version: 0.0.0-automated
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package meta_api

type InlineResponse200 struct {
	ColumnId       string                       `json:"column_id"`
	RelationSchema string                       `json:"relation_schema"`
	RelationName   string                       `json:"relation_name"`
	ColumnName     string                       `json:"column_name"`
	Privileges     []ColumnprivilegesPrivileges `json:"privileges"`
}
