/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type CreateFunctionBody struct {
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	Body      string `json:"body"`
	VerifyJwt bool   `json:"verify_jwt,omitempty"`
}
