/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type AttributeValue struct {
	Default_ *OneOfAttributeValueDefault_ `json:"default,omitempty"`
	Name     string                       `json:"name,omitempty"`
	Names    []string                     `json:"names,omitempty"`
}
