/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type ServiceHealthResponse struct {
	Info    *OneOfServiceHealthResponseInfo `json:"info,omitempty"`
	Name    string                          `json:"name"`
	Healthy bool                            `json:"healthy"`
	Status  string                          `json:"status"`
	Error_  string                          `json:"error,omitempty"`
}
