/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type V1OrganizationMemberResponse struct {
	UserId     string `json:"user_id"`
	UserName   string `json:"user_name"`
	Email      string `json:"email,omitempty"`
	RoleName   string `json:"role_name"`
	MfaEnabled bool   `json:"mfa_enabled"`
}
