/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type RealtimeHealthResponse struct {
	Healthy          bool    `json:"healthy"`
	DbConnected      bool    `json:"db_connected"`
	ConnectedCluster float64 `json:"connected_cluster"`
}
