/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type V1PgbouncerConfigResponse struct {
	PoolMode                string  `json:"pool_mode,omitempty"`
	DefaultPoolSize         float64 `json:"default_pool_size,omitempty"`
	IgnoreStartupParameters string  `json:"ignore_startup_parameters,omitempty"`
	MaxClientConn           float64 `json:"max_client_conn,omitempty"`
	ConnectionString        string  `json:"connection_string,omitempty"`
}
