/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type NetworkRestrictionsRequest struct {
	DbAllowedCidrs   []string `json:"dbAllowedCidrs"`
	DbAllowedCidrsV6 []string `json:"dbAllowedCidrsV6,omitempty"`
}
