/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type AuthConfigResponse struct {
	SmtpAdminEmail     string  `json:"smtp_admin_email,omitempty"`
	SmtpHost           string  `json:"smtp_host,omitempty"`
	SmtpPort           string  `json:"smtp_port,omitempty"`
	SmtpUser           string  `json:"smtp_user,omitempty"`
	SmtpPass           string  `json:"smtp_pass,omitempty"`
	SmtpMaxFrequency   float64 `json:"smtp_max_frequency,omitempty"`
	SmtpSenderName     string  `json:"smtp_sender_name,omitempty"`
	RateLimitEmailSent float64 `json:"rate_limit_email_sent,omitempty"`
}
