/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type BillingPlanId string

// List of BillingPlanId
const (
	FREE_BillingPlanId       BillingPlanId = "free"
	PRO_BillingPlanId        BillingPlanId = "pro"
	TEAM_BillingPlanId       BillingPlanId = "team"
	ENTERPRISE_BillingPlanId BillingPlanId = "enterprise"
)
