/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type V1BackupsResponsePhysicalBackupData struct {
	EarliestPhysicalBackupDateUnix float64 `json:"earliest_physical_backup_date_unix,omitempty"`
	LatestPhysicalBackupDateUnix   float64 `json:"latest_physical_backup_date_unix,omitempty"`
}
