/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type CreateProviderBody struct {
	// What type of provider will be created
	Type_            string            `json:"type"`
	MetadataXml      string            `json:"metadata_xml,omitempty"`
	MetadataUrl      string            `json:"metadata_url,omitempty"`
	Domains          []string          `json:"domains,omitempty"`
	AttributeMapping *AttributeMapping `json:"attribute_mapping,omitempty"`
}
