/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type NetworkRestrictionsResponse struct {
	Entitlement string                      `json:"entitlement"`
	Config      *NetworkRestrictionsRequest `json:"config"`
	OldConfig   *NetworkRestrictionsRequest `json:"old_config,omitempty"`
	Status      string                      `json:"status"`
}
