/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type ReadOnlyStatusResponse struct {
	Enabled             bool   `json:"enabled"`
	OverrideEnabled     bool   `json:"override_enabled"`
	OverrideActiveUntil string `json:"override_active_until"`
}
