/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type CreateBranchBody struct {
	BranchName string `json:"branch_name"`
	GitBranch  string `json:"git_branch,omitempty"`
	Region     string `json:"region,omitempty"`
}
