/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type BranchResponse struct {
	Id               string  `json:"id"`
	Name             string  `json:"name"`
	ProjectRef       string  `json:"project_ref"`
	ParentProjectRef string  `json:"parent_project_ref"`
	IsDefault        bool    `json:"is_default"`
	GitBranch        string  `json:"git_branch,omitempty"`
	PrNumber         float64 `json:"pr_number,omitempty"`
	ResetOnPush      bool    `json:"reset_on_push"`
	CreatedAt        string  `json:"created_at"`
	UpdatedAt        string  `json:"updated_at"`
}
