/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type ProjectRefResponse struct {
	Id   float64 `json:"id"`
	Ref  string  `json:"ref"`
	Name string  `json:"name"`
}
