/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type ProjectVersion struct {
	PostgresVersion float64 `json:"postgres_version"`
	AppVersion      string  `json:"app_version"`
}
