/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type SnippetMeta struct {
	Id          string          `json:"id"`
	InsertedAt  string          `json:"inserted_at"`
	UpdatedAt   string          `json:"updated_at"`
	Type_       string          `json:"type"`
	Visibility  string          `json:"visibility"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Project     *SnippetProject `json:"project"`
	Owner       *SnippetUser    `json:"owner"`
	UpdatedBy   *SnippetUser    `json:"updated_by"`
}
