/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type SamlDescriptor struct {
	Id               string            `json:"id"`
	EntityId         string            `json:"entity_id"`
	MetadataUrl      string            `json:"metadata_url,omitempty"`
	MetadataXml      string            `json:"metadata_xml,omitempty"`
	AttributeMapping *AttributeMapping `json:"attribute_mapping,omitempty"`
}
