/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type PostgresConfigResponse struct {
	StatementTimeout              string `json:"statement_timeout,omitempty"`
	EffectiveCacheSize            string `json:"effective_cache_size,omitempty"`
	MaintenanceWorkMem            string `json:"maintenance_work_mem,omitempty"`
	MaxConnections                int32  `json:"max_connections,omitempty"`
	MaxLocksPerTransaction        int32  `json:"max_locks_per_transaction,omitempty"`
	MaxParallelMaintenanceWorkers int32  `json:"max_parallel_maintenance_workers,omitempty"`
	MaxParallelWorkers            int32  `json:"max_parallel_workers,omitempty"`
	MaxParallelWorkersPerGather   int32  `json:"max_parallel_workers_per_gather,omitempty"`
	MaxWorkerProcesses            int32  `json:"max_worker_processes,omitempty"`
	SharedBuffers                 string `json:"shared_buffers,omitempty"`
	WorkMem                       string `json:"work_mem,omitempty"`
	SessionReplicationRole        string `json:"session_replication_role,omitempty"`
}
