/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type V1BackupsResponse struct {
	Region             string                               `json:"region"`
	WalgEnabled        bool                                 `json:"walg_enabled"`
	PitrEnabled        bool                                 `json:"pitr_enabled"`
	Backups            []V1Backup                           `json:"backups"`
	PhysicalBackupData *V1BackupsResponsePhysicalBackupData `json:"physical_backup_data"`
}
