/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type FunctionSlugResponse struct {
	Id             string  `json:"id"`
	Slug           string  `json:"slug"`
	Name           string  `json:"name"`
	Status         string  `json:"status"`
	Version        float64 `json:"version"`
	CreatedAt      float64 `json:"created_at"`
	UpdatedAt      float64 `json:"updated_at"`
	VerifyJwt      bool    `json:"verify_jwt,omitempty"`
	ImportMap      bool    `json:"import_map,omitempty"`
	EntrypointPath string  `json:"entrypoint_path,omitempty"`
	ImportMapPath  string  `json:"import_map_path,omitempty"`
}
