/*
 * Supabase API (v1)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package management_api

type UpdateCustomHostnameResponse struct {
	Status         string       `json:"status"`
	CustomHostname string       `json:"custom_hostname"`
	Data           *interface{} `json:"data"`
}
