package generator

import (
	"fmt"
	"path/filepath"
	"text/template"

	"github.com/sev-2/raiden"
	"github.com/sev-2/raiden/pkg/utils"
)

var mainFunctionDirTemplate = "/cmd/%s"
var mainFunctionTemplate = `// Code generated by raiden-cli; DO NOT EDIT.
package main
{{ if gt (len .Imports) 0 }}
import(
{{- range .Imports}}
	"{{.}}"
{{- end}}
)
{{ end }}

func main() {
	config := raiden.LoadConfig(nil)

	controllerRegistry := raiden.NewControllerRegistry()
	controllerRegistry.Register(
		raiden.HealthHandler,
		{{- range .Controllers}}
		controllers.{{.}},
		{{- end}}
	)

	// Setup server
	app := raiden.NewServer(config, controllerRegistry.Controllers)
	app.Run()
}
`

func GenerateMainFunction(config raiden.Config, controllerPackage string, controllerNames []string) error {
	cmdFolderPath := filepath.Join(config.ProjectName, "cmd")
	if exist := utils.IsFolderExists(cmdFolderPath); !exist {
		if err := utils.CreateFolder(cmdFolderPath); err != nil {
			return err
		}
	}

	mainFunctionDir := fmt.Sprintf(mainFunctionDirTemplate, config.ProjectName)
	folderPath := filepath.Join(config.ProjectName, mainFunctionDir)
	err := utils.CreateFolder(folderPath)
	if err != nil {
		return err
	}

	tmpl, err := template.New("mainFunctionTemplate").Parse(mainFunctionTemplate)
	if err != nil {
		return fmt.Errorf("error parsing template : %v", err)
	}

	// Create or open the output file
	file, err := createFile(getAbsolutePath(folderPath), config.ProjectName, "go")
	if err != nil {
		return fmt.Errorf("failed create file %s : %v", config.ProjectName, err)
	}
	defer file.Close()

	// setup template parameters
	importPaths := []string{
		"github.com/sev-2/raiden",
	}

	if len(controllerNames) > 0 {
		importPaths = append(importPaths, controllerPackage)
	}

	// Execute the template and write to the file
	err = tmpl.Execute(file, map[string]any{
		"Imports":     importPaths,
		"Controllers": controllerNames,
	})
	if err != nil {
		return fmt.Errorf("error executing template: %v", err)
	}

	return nil
}
