package generator

import (
	"fmt"
	"io/fs"
	"path/filepath"
	"strings"

	"github.com/hashicorp/go-hclog"
	"github.com/sev-2/raiden/pkg/logger"
	"github.com/sev-2/raiden/pkg/utils"
)

var PolicyRegisterLogger hclog.Logger = logger.HcLog().Named("generator.policy_register")

// ----- Define type, variable and constant -----
type (
	GenerateRegisterPolicyData struct {
		Imports  []string
		Package  string
		Policies []string
	}
)

const (
	PolicyRegisterFilename = "policies.go"
	PolicyRegisterDir      = "internal/bootstrap"
	PolicyRegisterTemplate = `// Code generated by raiden-cli; DO NOT EDIT.
package {{ .Package }}
{{if gt (len .Imports) 0 }}
import (
{{- range .Imports}}
	{{.}}
{{- end}}
)
{{end }}
func RegisterPolicies() {
	resource.RegisterPolicies(
		{{- range .Policies}}
		&policies.{{.}}{},
		{{- end}}
	)
}
`
)

func GeneratePolicyRegister(basePath string, projectName string, generateFn GenerateFn) error {
	policyRegisterDir := filepath.Join(basePath, PolicyRegisterDir)
	PolicyRegisterLogger.Trace("create bootstrap folder if not exist", "path", policyRegisterDir)
	if exist := utils.IsFolderExists(policyRegisterDir); !exist {
		if err := utils.CreateFolder(policyRegisterDir); err != nil {
			return err
		}
	}

	policyDir := filepath.Join(basePath, PolicyDir)
	PolicyRegisterLogger.Trace("create policies folder if not exist", "path", policyDir)
	if exist := utils.IsFolderExists(policyDir); !exist {
		if err := utils.CreateFolder(policyDir); err != nil {
			return err
		}
	}

	policyList, err := WalkScanPolicy(policyDir)
	if err != nil {
		return err
	}

	input, err := createPolicyRegisterInput(projectName, policyRegisterDir, policyList)
	if err != nil {
		return err
	}

	writer := &FileWriter{FilePath: input.OutputPath}

	PolicyRegisterLogger.Debug("generate policy register", "path", input.OutputPath)
	return generateFn(input, writer)
}

func createPolicyRegisterInput(projectName string, policyRegisterDir string, policyList []string) (input GenerateInput, err error) {
	filePath := filepath.Join(policyRegisterDir, PolicyRegisterFilename)

	imports := []string{
		fmt.Sprintf("%q", "github.com/sev-2/raiden/pkg/resource"),
	}

	if len(policyList) > 0 {
		policiesImportPath := fmt.Sprintf("%s/internal/policies", utils.ToGoModuleName(projectName))
		imports = append(imports, fmt.Sprintf("%q", policiesImportPath))
	}

	data := GenerateRegisterPolicyData{
		Package:  "bootstrap",
		Imports:  imports,
		Policies: policyList,
	}

	input = GenerateInput{
		BindData:     data,
		Template:     PolicyRegisterTemplate,
		TemplateName: "policyRegisterTemplate",
		OutputPath:   filePath,
	}

	return
}

func WalkScanPolicy(policyDir string) ([]string, error) {
	PolicyRegisterLogger.Trace("scan all policies", "path", policyDir)

	policies := make([]string, 0)
	err := filepath.Walk(policyDir, func(path string, info fs.FileInfo, err error) error {
		if strings.HasSuffix(path, ".go") {
			PolicyRegisterLogger.Trace("collect policies", "file-path", path)
			ps, e := getStructByBaseName(path, "PolicyBase")
			if e != nil {
				return e
			}

			policies = append(policies, ps...)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	return policies, nil
}
