// Code generated by raiden-cli; DO NOT EDIT.
package main

import (
	"github.com/sev-2/raiden"
	"github.com/sev-2/raiden/examples/todo-app/controllers"
	"github.com/sev-2/raiden/pkg/logger"
	"github.com/sev-2/raiden/pkg/utils"
)

func main() {
	currDir, err := utils.GetCurrentDirectory()
	if err != nil {
		logger.Panic(err)
	}
	configPath := currDir + "/examples/todo-app/configs/app.yaml"
	config := raiden.LoadConfig(&configPath)

	controllerRegistry := raiden.NewControllerRegistry()
	controllerRegistry.Register(
		raiden.HealthHandler,
		controllers.HelloWordHandler,
		controllers.GreetingHandler,
	)

	// Setup server
	app := raiden.NewServer(config, controllerRegistry.Controllers)
	app.Run()
}
